apiVersion: apps/v1   # Changed from v1 to apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: webapps
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:5.0.4
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.1"
          requests:
            memory: "200Mi"
            cpu: "70m"
      volumes:
      - name: redis-data
        emptyDir: {}
---
apiVersion: v1    # This is correct for Service
kind: Service
metadata:
  name: redis
  namespace: webapps
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis-port
  selector:
    app: redis
