apiVersion: v1
kind: Deployment
metadata:
  name: redis
  namespace: webapps
spec:
  replicas: 1  # Adjust this value based on your requirements
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:5.0.4  # Use the desired Redis version
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data  # Path where Redis will store its data
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.1"
          requests:
            memory: "200Mi"
            cpu: "70m"
      volumes:
      - name: redis-data
        emptyDir: {}  # Use an emptyDir for temporary storage; consider using a PVC for persistence

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: webapps
spec:
  type: ClusterIP  # Use ClusterIP for internal access; change to LoadBalancer if external access is needed
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis-port
  selector:
    app: redis

